#!/bin/sh

# CREATE DIRECTORIES
mkdir -p /opt/pi4j
mkdir -p /opt/pi4j/lib
mkdir -p /opt/pi4j/bin
mkdir -p /opt/pi4j/examples

# SET READ+WRITE PERMISSIONS FOR EXAMPLES DIRECTORY
chmod -f -R a+rw /opt/pi4j/examples


