#!/bin/sh

# CREATE DIRECTORIES
mkdir -p /opt/pi4j
mkdir -p /opt/pi4j/lib
mkdir -p /opt/pi4j/bin
mkdir -p /opt/pi4j/examples
mkdir -p /opt/pi4j/examples/bananapi
mkdir -p /opt/pi4j/examples/bananapro
mkdir -p /opt/pi4j/examples/odroid
mkdir -p /opt/pi4j/examples/odroid/c1
mkdir -p /opt/pi4j/examples/odroid/xu4

# SET READ+WRITE PERMISSIONS FOR EXAMPLES DIRECTORY
chmod -f -R a+rw /opt/pi4j/examples


