#!/bin/bash
set -e # exit on error

###
# #%L
# **********************************************************************
# ORGANIZATION  :  Pi4J
# PROJECT       :  Pi4J :: Java Examples (for Odroid XU4)
# FILENAME      :  run
#
# This file is part of the Pi4J project. More information about
# this project can be found here:  http://www.pi4j.com/
# **********************************************************************
# %%
# Copyright (C) 2012 - 2018 Pi4J
# %%
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Lesser Public License for more details.
#
# You should have received a copy of the GNU General Lesser Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/lgpl-3.0.html>.
# #L%
###

# CHECK FOR MISSING CLI ARGUMENTS
if [ $# -eq 0 ]; then
    echo
    echo "No program name argument supplied!"
    echo "Use 'run <ProgramName>'"
    echo
    exit 1;
fi

# DEFINED APP NAMESPACE
NAMESPACE=odroid.xu4.

# GET PROGRAM NAME FROM FIRST CLI ARG
NAME=$1;

# REMOVE .java FILE EXTENSION FROM NAME ARG IF EXISTS
NAME=${NAME/.java/}

# REMOVE NAMESPACE FROM NAME ARG IF EXISTS
NAME=${NAME#$NAMESPACE}

# LAUNCH PI4J SAMPLE PROGRAM
set -x #echo on
sudo java -classpath .:classes:'*':classes:/opt/pi4j/lib/'*' $NAMESPACE$NAME $@
