#!/bin/sh

###
# #%L
# **********************************************************************
# ORGANIZATION  :  Pi4J
# PROJECT       :  Pi4J :: Java Examples
# FILENAME      :  build.sh  
# 
# This file is part of the Pi4J project. More information about 
# this project can be found here:  http://www.pi4j.com/
# **********************************************************************
# %%
# Copyright (C) 2012-2013 Pi4J
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
###

cd $(dirname $(readlink -f $0))

echo "---------------------------------------------------------"

# THE FOLLOWING INSTRUCTIONS WILL COMPILE ALL THE EXAMPLE PROJECTS
echo "[01 of 35] ... compiling : BlinkGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . BlinkGpioExample.java

echo "[02 of 35] ... compiling : BlinkTriggerGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . BlinkTriggerGpioExample.java

echo "[03 of 35] ... compiling : ComputeModuleGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . ComputeModuleGpioExample.java

echo "[04 of 35] ... compiling : ControlGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . ControlGpioExample.java

echo "[05 of 35] ... compiling : CylonGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . CylonGpioExample.java

echo "[06 of 35] ... compiling : DebounceGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . DebounceGpioExample.java

echo "[07 of 35] ... compiling : FrequencyGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . FrequencyGpioExample.java

echo "[08 of 35] ... compiling : I2CWiiMotionPlusExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . I2CWiiMotionPlusExample.java

echo "[09 of 35] ... compiling : ListenGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . ListenGpioExample.java

echo "[10 of 35] ... compiling : ListenMultipleGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . ListenMultipleGpioExample.java

echo "[11 of 35] ... compiling : MCP23017GpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . MCP23017GpioExample.java

echo "[12 of 35] ... compiling : MCP23S17GpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . MCP23S17GpioExample.java

echo "[13 of 35] ... compiling : MCP4725GpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . MCP4725GpioExample.java

echo "[14 of 35] ... compiling : MultipurposePinGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . MultipurposePinGpioExample.java

echo "[15 of 35] ... compiling : OlimexGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . OlimexGpioExample.java

echo "[16 of 35] ... compiling : PCF8574GpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . PCF8574GpioExample.java

echo "[17 of 35] ... compiling : PCA9685GpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . PCA9685GpioExample.java

echo "[18 of 35] ... compiling : PCA9685GpioServoExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . PCA9685GpioServoExample.java

echo "[19 of 35] ... compiling : PibrellaExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . PibrellaExample.java

echo "[20 of 35] ... compiling : PiFaceExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . PiFaceExample.java

echo "[21 of 35] ... compiling : PiFaceGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . PiFaceGpioExample.java

echo "[22 of 35] ... compiling : SerialExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . SerialExample.java

echo "[23 of 35] ... compiling : ShutdownGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . ShutdownGpioExample.java

echo "[24 of 35] ... compiling : SpiExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . SpiExample.java

echo "[25 of 35] ... compiling : StepperMotorGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . StepperMotorGpioExample.java

echo "[26 of 35] ... compiling : SystemInfoExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . SystemInfoExample.java

echo "[27 of 35] ... compiling : TriggerGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . TriggerGpioExample.java

echo "[28 of 35] ... compiling : UsageGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . UsageGpioExample.java

echo "[29 of 35] ... compiling : WiringPiGpioExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WiringPiGpioExample.java

echo "[30 of 35] ... compiling : WiringPiGpioInterruptExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WiringPiGpioInterruptExample.java

echo "[31 of 35] ... compiling : WiringPiGpioInterruptExample2.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WiringPiGpioInterruptExample2.java

echo "[32 of 35] ... compiling : WiringPiSerialExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WiringPiSerialExample.java

echo "[33 of 35] ... compiling : WiringPiSoftPWMExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WiringPiSoftPWMExample.java

echo "[34 of 35] ... compiling : WiringPiSPIExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WiringPiSPIExample.java

echo "[35 of 35] ... compiling : WDTExample.java"
javac -classpath .:classes:/opt/pi4j/lib/'*' -d . WDTExample.java

echo "---------------------------------------------------------"

# THE FOLLOWING INSTRUCTIONS WILL EXECUTE ONE OF THE EXAMPLES
# sudo java -classpath .:classes:/opt/pi4j/lib/'*' BlinkGpioExample
echo "The following command syntax can be used to execute the sample projects:"
echo "  sudo java -classpath .:classes:/opt/pi4j/lib/'*' BlinkGpioExample"
echo "---------------------------------------------------------"