#!/bin/bash
set -e # exit on error

###
# #%L
# **********************************************************************
# ORGANIZATION  :  Pi4J
# PROJECT       :  Pi4J :: Java Examples (for RaspberryPi)
# FILENAME      :  run
#
# This file is part of the Pi4J project. More information about
# this project can be found here:  https://pi4j.com/
# **********************************************************************
# %%
# Copyright (C) 2012 - 2020 Pi4J
# %%
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# #L%
###

# CHECK FOR MISSING CLI ARGUMENTS
if [ $# -eq 0 ]; then
    echo
    echo "No program name argument supplied!"
    echo "Use 'run <ProgramName>'"
    echo
    exit 1;
fi

# DEFINED APP NAMESPACE
NAMESPACE=

# GET PROGRAM NAME FROM FIRST CLI ARG
NAME=$1;

# REMOVE .java FILE EXTENSION FROM NAME ARG IF EXISTS
NAME=${NAME/.java/}

# REMOVE NAMESPACE FROM NAME ARG IF EXISTS
NAME=${NAME#$NAMESPACE}

# LAUNCH PI4J SAMPLE PROGRAM
set -x #echo on
sudo java -classpath .:classes:'*':classes:/opt/pi4j/lib/'*' $NAMESPACE$NAME $@
