/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_Shift */

#ifndef _Included_com_pi4j_wiringpi_Shift
#define _Included_com_pi4j_wiringpi_Shift
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pi4j_wiringpi_Shift_LSBFIRST
#define com_pi4j_wiringpi_Shift_LSBFIRST 0L
#undef com_pi4j_wiringpi_Shift_MSBFIRST
#define com_pi4j_wiringpi_Shift_MSBFIRST 1L
/*
 * Class:     com_pi4j_wiringpi_Shift
 * Method:    shiftIn
 * Signature: (BBB)B
 */
JNIEXPORT jbyte JNICALL Java_com_pi4j_wiringpi_Shift_shiftIn
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     com_pi4j_wiringpi_Shift
 * Method:    shiftOut
 * Signature: (BBBB)V
 */
JNIEXPORT void JNICALL Java_com_pi4j_wiringpi_Shift_shiftOut
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
