/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_GpioInterrupt */

#ifndef _Included_com_pi4j_wiringpi_GpioInterrupt
#define _Included_com_pi4j_wiringpi_GpioInterrupt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pi4j_wiringpi_GpioInterrupt
 * Method:    enablePinStateChangeCallback
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_GpioInterrupt_enablePinStateChangeCallback
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioInterrupt
 * Method:    disablePinStateChangeCallback
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_GpioInterrupt_disablePinStateChangeCallback
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
