/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_GpioUtil */

#ifndef _Included_com_pi4j_wiringpi_GpioUtil
#define _Included_com_pi4j_wiringpi_GpioUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pi4j_wiringpi_GpioUtil_DIRECTION_IN
#define com_pi4j_wiringpi_GpioUtil_DIRECTION_IN 0L
#undef com_pi4j_wiringpi_GpioUtil_DIRECTION_OUT
#define com_pi4j_wiringpi_GpioUtil_DIRECTION_OUT 1L
#undef com_pi4j_wiringpi_GpioUtil_EDGE_NONE
#define com_pi4j_wiringpi_GpioUtil_EDGE_NONE 0L
#undef com_pi4j_wiringpi_GpioUtil_EDGE_BOTH
#define com_pi4j_wiringpi_GpioUtil_EDGE_BOTH 1L
#undef com_pi4j_wiringpi_GpioUtil_EDGE_RISING
#define com_pi4j_wiringpi_GpioUtil_EDGE_RISING 2L
#undef com_pi4j_wiringpi_GpioUtil_EDGE_FALLING
#define com_pi4j_wiringpi_GpioUtil_EDGE_FALLING 3L
/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    export
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_pi4j_wiringpi_GpioUtil_export
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    unexport
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_pi4j_wiringpi_GpioUtil_unexport
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    isExported
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pi4j_wiringpi_GpioUtil_isExported
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    setEdgeDetection
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pi4j_wiringpi_GpioUtil_setEdgeDetection
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    getEdgeDetection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_GpioUtil_getEdgeDetection
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    setDirection
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pi4j_wiringpi_GpioUtil_setDirection
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_GpioUtil
 * Method:    getDirection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_GpioUtil_getDirection
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
