/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_Gertboard */

#ifndef _Included_com_pi4j_wiringpi_Gertboard
#define _Included_com_pi4j_wiringpi_Gertboard
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pi4j_wiringpi_Gertboard_SPI_ADC_SPEED
#define com_pi4j_wiringpi_Gertboard_SPI_ADC_SPEED 1000000L
#undef com_pi4j_wiringpi_Gertboard_SPI_DAC_SPEED
#define com_pi4j_wiringpi_Gertboard_SPI_DAC_SPEED 1000000L
#undef com_pi4j_wiringpi_Gertboard_SPI_A2D
#define com_pi4j_wiringpi_Gertboard_SPI_A2D 0L
#undef com_pi4j_wiringpi_Gertboard_SPI_D2A
#define com_pi4j_wiringpi_Gertboard_SPI_D2A 1L
/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardAnalogWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardAnalogWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardAnalogRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardAnalogRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardSPISetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardSPISetup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
