/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_Nes */

#ifndef _Included_com_pi4j_wiringpi_Nes
#define _Included_com_pi4j_wiringpi_Nes
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pi4j_wiringpi_Nes_NES_RIGHT
#define com_pi4j_wiringpi_Nes_NES_RIGHT 1L
#undef com_pi4j_wiringpi_Nes_NES_LEFT
#define com_pi4j_wiringpi_Nes_NES_LEFT 2L
#undef com_pi4j_wiringpi_Nes_NES_DOWN
#define com_pi4j_wiringpi_Nes_NES_DOWN 4L
#undef com_pi4j_wiringpi_Nes_NES_UP
#define com_pi4j_wiringpi_Nes_NES_UP 8L
#undef com_pi4j_wiringpi_Nes_NES_START
#define com_pi4j_wiringpi_Nes_NES_START 16L
#undef com_pi4j_wiringpi_Nes_NES_SELECT
#define com_pi4j_wiringpi_Nes_NES_SELECT 32L
#undef com_pi4j_wiringpi_Nes_NES_B
#define com_pi4j_wiringpi_Nes_NES_B 64L
#undef com_pi4j_wiringpi_Nes_NES_A
#define com_pi4j_wiringpi_Nes_NES_A 128L
#undef com_pi4j_wiringpi_Nes_PULSE_TIME
#define com_pi4j_wiringpi_Nes_PULSE_TIME 25L
#undef com_pi4j_wiringpi_Nes_MAX_NES_JOYSTICKS
#define com_pi4j_wiringpi_Nes_MAX_NES_JOYSTICKS 8L
/*
 * Class:     com_pi4j_wiringpi_Nes
 * Method:    setupNesJoystick
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Nes_setupNesJoystick
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_Nes
 * Method:    readNesJoystick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Nes_readNesJoystick
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
