/*
 * #%L
 * **********************************************************************
 * ORGANIZATION  :  Pi4J
 * PROJECT       :  Pi4J :: JNI Native Library
 * FILENAME      :  com_pi4j_wiringpi_Gertboard.h  
 * 
 * This file is part of the Pi4J project. More information about 
 * this project can be found here:  http://www.pi4j.com/
 * **********************************************************************
 * %%
 * Copyright (C) 2012 - 2014 Pi4J
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_Gertboard */

#ifndef _Included_com_pi4j_wiringpi_Gertboard
#define _Included_com_pi4j_wiringpi_Gertboard
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pi4j_wiringpi_Gertboard_SPI_ADC_SPEED
#define com_pi4j_wiringpi_Gertboard_SPI_ADC_SPEED 1000000L
#undef com_pi4j_wiringpi_Gertboard_SPI_DAC_SPEED
#define com_pi4j_wiringpi_Gertboard_SPI_DAC_SPEED 1000000L
#undef com_pi4j_wiringpi_Gertboard_SPI_A2D
#define com_pi4j_wiringpi_Gertboard_SPI_A2D 0L
#undef com_pi4j_wiringpi_Gertboard_SPI_D2A
#define com_pi4j_wiringpi_Gertboard_SPI_D2A 1L
/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardAnalogWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardAnalogWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardAnalogRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardAnalogRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardSPISetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardSPISetup
  (JNIEnv *, jclass);

/*
 * Class:     com_pi4j_wiringpi_Gertboard
 * Method:    gertboardAnalogSetup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Gertboard_gertboardAnalogSetup
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
