/*
 * #%L
 * **********************************************************************
 * ORGANIZATION  :  Pi4J
 * PROJECT       :  Pi4J :: JNI Native Library
 * FILENAME      :  com_pi4j_wiringpi_Nes.h
 * 
 * This file is part of the Pi4J project. More information about
 * this project can be found here:  https://pi4j.com/
 * **********************************************************************
 * %%
 * Copyright (C) 2012 - 2019 Pi4J
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi4j_wiringpi_Nes */

#ifndef _Included_com_pi4j_wiringpi_Nes
#define _Included_com_pi4j_wiringpi_Nes
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pi4j_wiringpi_Nes_NES_RIGHT
#define com_pi4j_wiringpi_Nes_NES_RIGHT 1L
#undef com_pi4j_wiringpi_Nes_NES_LEFT
#define com_pi4j_wiringpi_Nes_NES_LEFT 2L
#undef com_pi4j_wiringpi_Nes_NES_DOWN
#define com_pi4j_wiringpi_Nes_NES_DOWN 4L
#undef com_pi4j_wiringpi_Nes_NES_UP
#define com_pi4j_wiringpi_Nes_NES_UP 8L
#undef com_pi4j_wiringpi_Nes_NES_START
#define com_pi4j_wiringpi_Nes_NES_START 16L
#undef com_pi4j_wiringpi_Nes_NES_SELECT
#define com_pi4j_wiringpi_Nes_NES_SELECT 32L
#undef com_pi4j_wiringpi_Nes_NES_B
#define com_pi4j_wiringpi_Nes_NES_B 64L
#undef com_pi4j_wiringpi_Nes_NES_A
#define com_pi4j_wiringpi_Nes_NES_A 128L
#undef com_pi4j_wiringpi_Nes_PULSE_TIME
#define com_pi4j_wiringpi_Nes_PULSE_TIME 25L
#undef com_pi4j_wiringpi_Nes_MAX_NES_JOYSTICKS
#define com_pi4j_wiringpi_Nes_MAX_NES_JOYSTICKS 8L
/*
 * Class:     com_pi4j_wiringpi_Nes
 * Method:    setupNesJoystick
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Nes_setupNesJoystick
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_pi4j_wiringpi_Nes
 * Method:    readNesJoystick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pi4j_wiringpi_Nes_readNesJoystick
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
